# Generated by Django 2.1.7 on 2019-04-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='input_data',
            new_name='formdata',
        ),
    ]
