# Generated by Django 2.1.7 on 2019-04-02 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0002_auto_20190401_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formdata',
            new_name='OrderForm',
        ),
    ]
