# Generated by Django 2.1.7 on 2019-04-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('former', '0003_auto_20190401_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='state',
            new_name='state_code',
        ),
        migrations.AlterField(
            model_name='orderform',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
