# Generated by Django 2.2.2 on 2019-07-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20190629_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='vibe',
        ),
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(default='Visual Inspiration', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='visual_vibes'),
        ),
        migrations.AddField(
            model_name='story',
            name='music',
            field=models.CharField(default='Musical Inspiration', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='music_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Vibrary',
        ),
    ]
