# Generated by Django 2.2.2 on 2019-07-03 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20190702_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
