# Generated by Django 2.2.2 on 2019-07-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-id'], 'verbose_name_plural': 'stories'},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='caption',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='story',
            name='art_link',
            field=models.URLField(blank=True),
        ),
    ]
