# Generated by Django 2.2.2 on 2019-07-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20190703_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='artist',
            new_name='artwork',
        ),
    ]
